runtime: python39
env: standard
instance_class: F1
entrypoint: gunicorn -b :$PORT main:app
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
- url: /.*
  script: auto

